
void throw_exception();

int main() {
    throw_exception();

    return 0;
}